<?php

namespace App\Services;

use DateTimeInterface;
use Generator;
use Illuminate\Database\Connection;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\ValidationException;
use RuntimeException;

class DatabaseBackupService
{
    private const ARCHIVE_DIRECTORY = 'database-archives';

    public function information(): array
    {
        $connection = DB::connection();
        $database = (string) $connection->getDatabaseName();

        return [
            'driver' => $connection->getDriverName(),
            'name' => $connection->getDriverName() === 'sqlite' ? basename($database) : $database,
            'tables' => count($this->tables($connection)),
        ];
    }

    public function filename(): string
    {
        return 'snapie-database-'.now()->format('Y-m-d_His_u').'.sql';
    }

    /** @return array{name: string, path: string, size: int, created_at: \Carbon\CarbonInterface} */
    public function archive(): array
    {
        $name = $this->filename();
        $path = self::ARCHIVE_DIRECTORY.'/'.$name;
        $disk = Storage::disk('local');
        $disk->makeDirectory(self::ARCHIVE_DIRECTORY);
        $handle = fopen($disk->path($path), 'wb');

        if ($handle === false) {
            throw new RuntimeException('The database archive could not be created.');
        }

        try {
            foreach ($this->stream() as $chunk) {
                if (fwrite($handle, $chunk) === false) {
                    throw new RuntimeException('The database archive could not be written completely.');
                }
            }
        } catch (\Throwable $exception) {
            fclose($handle);
            $disk->delete($path);
            throw $exception;
        }

        fclose($handle);

        return $this->details($name);
    }

    /** @return array{name: string, path: string, size: int, created_at: \Carbon\CarbonInterface} */
    public function import(UploadedFile $file): array
    {
        $header = substr($file->getContent(), 0, 4096);
        if (! str_contains($header, '-- SNAPIE database backup')) {
            throw ValidationException::withMessages([
                'database_file' => 'Upload a SQL backup generated by SNAPIE Database Management.',
            ]);
        }

        preg_match('/-- Driver:\s*([a-z0-9_]+)/i', $header, $matches);
        $uploadedDriver = strtolower($matches[1] ?? '');
        $currentDriver = strtolower(DB::connection()->getDriverName());
        $compatibleDrivers = ['mysql' => ['mysql', 'mariadb'], 'mariadb' => ['mysql', 'mariadb'], 'sqlite' => ['sqlite']];
        if (! in_array($uploadedDriver, $compatibleDrivers[$currentDriver] ?? [$currentDriver], true)) {
            throw ValidationException::withMessages([
                'database_file' => 'The uploaded '.$uploadedDriver.' backup is not compatible with the active '.$currentDriver.' database.',
            ]);
        }

        $name = $this->filename();
        $path = self::ARCHIVE_DIRECTORY.'/'.$name;
        $disk = Storage::disk('local');
        $disk->makeDirectory(self::ARCHIVE_DIRECTORY);
        $stream = fopen($file->getRealPath(), 'rb');
        if ($stream === false || ! $disk->writeStream($path, $stream)) {
            if (is_resource($stream)) {
                fclose($stream);
            }
            throw ValidationException::withMessages([
                'database_file' => 'The uploaded database backup could not be stored.',
            ]);
        }
        if (is_resource($stream)) {
            fclose($stream);
        }

        return $this->details($name);
    }

    public function archives(): \Illuminate\Support\Collection
    {
        $disk = Storage::disk('local');

        return collect($disk->files(self::ARCHIVE_DIRECTORY))
            ->filter(fn (string $path): bool => str_ends_with($path, '.sql'))
            ->map(fn (string $path): array => $this->details(basename($path)))
            ->sortByDesc('created_at')
            ->values();
    }

    /** @return array{name: string, path: string, size: int, created_at: \Carbon\CarbonInterface} */
    public function details(string $name): array
    {
        $path = $this->path($name);
        $disk = Storage::disk('local');
        abort_unless($disk->exists($path), 404);

        return [
            'name' => $name,
            'path' => $path,
            'size' => $disk->size($path),
            'created_at' => now()->createFromTimestamp($disk->lastModified($path)),
        ];
    }

    public function delete(string $name): void
    {
        $path = $this->path($name);
        abort_unless(Storage::disk('local')->exists($path), 404);
        Storage::disk('local')->delete($path);
    }

    /** @return array{name: string, path: string, size: int, created_at: \Carbon\CarbonInterface} */
    public function restore(string $name): array
    {
        $path = $this->path($name);
        $disk = Storage::disk('local');
        abort_unless($disk->exists($path), 404);
        $sql = $disk->get($path);
        $safetyArchive = $this->archive();
        $connection = DB::connection();
        $driver = $connection->getDriverName();

        if (! in_array($driver, ['mysql', 'mariadb', 'sqlite'], true)) {
            throw new RuntimeException("Database restores are not available for the {$driver} driver.");
        }

        if ($driver === 'sqlite') {
            $connection->statement('PRAGMA foreign_keys=OFF');
        } else {
            $connection->statement('SET FOREIGN_KEY_CHECKS=0');
        }

        try {
            foreach ($this->statements($sql) as $statement) {
                $normalized = strtoupper(trim($statement));
                if ($normalized === ''
                    || str_starts_with($normalized, 'PRAGMA FOREIGN_KEYS')
                    || str_starts_with($normalized, 'SET FOREIGN_KEY_CHECKS')
                    || str_starts_with($normalized, 'SET NAMES')
                    || in_array($normalized, ['BEGIN TRANSACTION', 'START TRANSACTION', 'COMMIT'], true)) {
                    continue;
                }

                $connection->unprepared($statement);
            }
        } finally {
            if ($driver === 'sqlite') {
                $connection->statement('PRAGMA foreign_keys=ON');
            } else {
                $connection->statement('SET FOREIGN_KEY_CHECKS=1');
            }
        }

        return $safetyArchive;
    }

    public function stream(): Generator
    {
        $connection = DB::connection();
        $driver = $connection->getDriverName();
        if (! in_array($driver, ['mysql', 'mariadb', 'sqlite'], true)) {
            throw new RuntimeException("Database backups are not available for the {$driver} driver.");
        }

        yield '-- SNAPIE database backup'.PHP_EOL;
        yield '-- Generated: '.now()->toIso8601String().PHP_EOL;
        yield '-- Driver: '.$driver.PHP_EOL.PHP_EOL;
        yield $driver === 'sqlite'
            ? 'PRAGMA foreign_keys=OFF;'.PHP_EOL.'BEGIN TRANSACTION;'.PHP_EOL.PHP_EOL
            : 'SET NAMES utf8mb4;'.PHP_EOL.'SET FOREIGN_KEY_CHECKS=0;'.PHP_EOL.'START TRANSACTION;'.PHP_EOL.PHP_EOL;

        foreach ($this->tables($connection) as $table) {
            $identifier = $this->quoteIdentifier($table['name'], $driver);
            yield 'DROP TABLE IF EXISTS '.$identifier.';'.PHP_EOL;
            yield rtrim($table['create'], "; \t\n\r\0\x0B").';'.PHP_EOL.PHP_EOL;
            yield from $this->tableRows($connection, $table['name'], $driver);
        }

        yield 'COMMIT;'.PHP_EOL;
        yield $driver === 'sqlite' ? 'PRAGMA foreign_keys=ON;'.PHP_EOL : 'SET FOREIGN_KEY_CHECKS=1;'.PHP_EOL;
    }

    private function tables(Connection $connection): array
    {
        if ($connection->getDriverName() === 'sqlite') {
            return collect($connection->select("SELECT name, sql FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' ORDER BY name"))
                ->filter(fn ($table) => filled($table->sql))
                ->map(fn ($table) => ['name' => $table->name, 'create' => $table->sql])
                ->values()
                ->all();
        }

        return collect($connection->select("SHOW FULL TABLES WHERE Table_type = 'BASE TABLE'"))
            ->map(function ($row) use ($connection): array {
                $name = (string) array_values((array) $row)[0];
                $createRow = (array) $connection->selectOne('SHOW CREATE TABLE '.$this->quoteIdentifier($name, 'mysql'));

                return ['name' => $name, 'create' => (string) array_values($createRow)[1]];
            })
            ->all();
    }

    private function tableRows(Connection $connection, string $table, string $driver): Generator
    {
        $batch = [];
        $columns = [];

        foreach ($connection->table($table)->cursor() as $row) {
            $values = (array) $row;
            if ($columns === []) {
                $columns = array_keys($values);
            }
            $batch[] = '('.collect($values)->map(fn ($value) => $this->quoteValue($connection, $value))->implode(', ').')';

            if (count($batch) >= 100) {
                yield $this->insertStatement($table, $columns, $batch, $driver);
                $batch = [];
            }
        }

        if ($batch !== []) {
            yield $this->insertStatement($table, $columns, $batch, $driver);
        }
    }

    private function insertStatement(string $table, array $columns, array $rows, string $driver): string
    {
        $columnList = collect($columns)->map(fn ($column) => $this->quoteIdentifier($column, $driver))->implode(', ');

        return 'INSERT INTO '.$this->quoteIdentifier($table, $driver).' ('.$columnList.') VALUES'.PHP_EOL
            .implode(','.PHP_EOL, $rows).';'.PHP_EOL.PHP_EOL;
    }

    private function quoteIdentifier(string $identifier, string $driver): string
    {
        return $driver === 'sqlite'
            ? '"'.str_replace('"', '""', $identifier).'"'
            : '`'.str_replace('`', '``', $identifier).'`';
    }

    private function quoteValue(Connection $connection, mixed $value): string
    {
        if ($value === null) {
            return 'NULL';
        }
        if (is_bool($value)) {
            return $value ? '1' : '0';
        }
        if (is_int($value) || is_float($value)) {
            return (string) $value;
        }
        if ($value instanceof DateTimeInterface) {
            $value = $value->format('Y-m-d H:i:s');
        }
        if (is_resource($value)) {
            $value = stream_get_contents($value);
        }

        $quoted = $connection->getPdo()->quote((string) $value);
        if ($quoted === false) {
            throw new RuntimeException('A database value could not be safely exported.');
        }

        return $quoted;
    }

    private function path(string $name): string
    {
        abort_unless((bool) preg_match('/\Asnapie-database-\d{4}-\d{2}-\d{2}_\d{6}(?:_\d{6})?\.sql\z/', $name), 404);

        return self::ARCHIVE_DIRECTORY.'/'.$name;
    }

    /** @return array<int, string> */
    private function statements(string $sql): array
    {
        $statements = [];
        $buffer = '';
        $quote = null;
        $escaped = false;
        $length = strlen($sql);

        for ($index = 0; $index < $length; $index++) {
            $character = $sql[$index];
            $buffer .= $character;

            if ($escaped) {
                $escaped = false;

                continue;
            }
            if ($quote !== null && $character === '\\') {
                $escaped = true;

                continue;
            }
            if (in_array($character, ["'", '"', '`'], true)) {
                if ($quote === null) {
                    $quote = $character;
                } elseif ($quote === $character) {
                    $next = $sql[$index + 1] ?? null;
                    if ($next === $character && $character !== '`') {
                        $buffer .= $next;
                        $index++;
                    } else {
                        $quote = null;
                    }
                }

                continue;
            }
            if ($character === ';' && $quote === null) {
                $statement = trim(substr($buffer, 0, -1));
                if ($statement !== '') {
                    $statements[] = $statement;
                }
                $buffer = '';
            }
        }

        if (trim($buffer) !== '') {
            $statements[] = trim($buffer);
        }

        return $statements;
    }
}
