@extends($layout)

@section('title', $project->title)
@section('page-title', 'Community Project')

@section('content')
    <section class="welcome-banner"><div><span class="eyebrow">{{ $project->reference_number }} · {{ $project->component->code }}</span><h2>{{ $project->title }}</h2><p>{{ $project->section?->code ?? 'Component-wide' }} · Proposed by {{ $project->proposer->name }} · {{ $project->location }}</p></div><div style="display:flex;gap:.6rem;flex-wrap:wrap">@if($canEdit)<a class="secondary-button" href="{{ route($routePrefix.'.community-projects.edit', $project) }}">Edit project</a>@endif<a class="secondary-button" href="{{ route($routePrefix.'.project-tasks.index', ['project_id' => $project->id]) }}">Task monitoring</a><a class="secondary-button" href="{{ route($routePrefix.'.evaluations.index') }}">Evaluations</a>@if($canManageImplementation)<a class="secondary-button" href="{{ route($routePrefix.'.project-tasks.create', $project) }}">Assign task</a>@endif<a class="secondary-button" href="{{ route($routePrefix.'.community-projects.index') }}">All projects</a></div></section>
    @if($errors->any())<div class="alert error"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

    <section class="dashboard-grid two-column" style="margin-bottom:1.25rem">
        <article class="card" style="padding:1.25rem"><span class="eyebrow">Project scope</span><h3>Beneficiaries and resources</h3><dl class="details-list"><div><dt>Beneficiaries</dt><dd>{{ $project->beneficiaries }}</dd></div><div><dt>Estimated reach</dt><dd>{{ $project->beneficiary_count ? number_format($project->beneficiary_count) : 'Not specified' }}</dd></div><div><dt>Location</dt><dd>{{ $project->location }}</dd></div><div><dt>Budget</dt><dd>₱{{ number_format((float) $project->budget, 2) }}</dd></div><div><dt>Timeline</dt><dd>{{ $project->start_date?->format('M d, Y') ?? 'Not set' }} – {{ $project->end_date?->format('M d, Y') ?? 'Not set' }}</dd></div></dl></article>
        <article class="card" style="padding:1.25rem"><span class="eyebrow">Current standing</span><h3>{{ $project->approvalLabel() }} · {{ $project->implementationLabel() }}</h3><p><strong>Approval notes:</strong><br>{{ $project->approval_notes ?: 'No approval notes recorded.' }}</p><p><strong>Implementation notes:</strong><br>{{ $project->implementation_notes ?: 'No implementation notes recorded.' }}</p>@if($project->approver)<p><small>Decision recorded by {{ $project->approver->name }} on {{ $project->approved_at?->format('M d, Y g:i A') }}.</small></p>@endif</article>
    </section>

    <section class="card" style="padding:1.25rem;margin-bottom:1.25rem"><span class="eyebrow">Project plan</span><h3>Community need and objectives</h3><h4>Description</h4><p style="white-space:pre-line">{{ $project->description }}</p><h4>Objectives</h4><p style="white-space:pre-line">{{ $project->objectives }}</p></section>

    @if($canApprove || $canManageImplementation)
        <section class="dashboard-grid two-column" style="margin-bottom:1.25rem">
            @if($canApprove)<form class="card" style="padding:1.25rem" method="POST" action="{{ route($routePrefix.'.community-projects.approval', $project) }}">@csrf @method('PUT')<span class="eyebrow">Authorized review</span><h3>Record approval decision</h3><label class="field-group"><span>Decision</span><select name="approval_status" required>@foreach(['approved' => 'Approve', 'needs_revision' => 'Return for revision', 'rejected' => 'Reject'] as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></label><label class="field-group"><span>Review notes</span><textarea name="approval_notes" rows="4" maxlength="3000" placeholder="Required for revision or rejection">{{ old('approval_notes', $project->approval_notes) }}</textarea></label><button class="primary-button" type="submit">Save decision</button></form>@endif
            @if($canManageImplementation)<form class="card" style="padding:1.25rem" method="POST" action="{{ route($routePrefix.'.community-projects.implementation', $project) }}">@csrf @method('PUT')<span class="eyebrow">Delivery tracking</span><h3>Implementation status</h3><label class="field-group"><span>Status</span><select name="implementation_status" required>@foreach($implementationStatuses as $value => $label)<option value="{{ $value }}" @selected($project->implementation_status === $value)>{{ $label }}</option>@endforeach</select></label><label class="field-group"><span>Implementation notes</span><textarea name="implementation_notes" rows="4" maxlength="3000">{{ old('implementation_notes', $project->implementation_notes) }}</textarea></label><button class="primary-button" type="submit">Update implementation</button></form>@endif
        </section>
    @endif

    <section class="card user-table-card">
        <div class="section-heading"><div><span class="eyebrow">Work plan and accomplishments</span><h3>Project activities</h3><p>Track scheduled work and record what was accomplished.</p></div></div>
        <div class="table-wrap"><table class="data-table"><thead><tr><th>Activity</th><th>Schedule</th><th>Status</th><th>Accomplishment</th><th>Recorded by</th></tr></thead><tbody>@forelse($project->activities as $activity)<tr><td><strong>{{ $activity->title }}</strong><small class="table-secondary-line">{{ $activity->description }}</small></td><td>{{ $activity->scheduled_date?->format('M d, Y') ?? 'Not set' }}</td><td>{{ $activityStatuses[$activity->status] ?? str($activity->status)->headline() }}</td><td>{{ $activity->accomplishment_notes ?: '—' }}@if($canManageImplementation)<details><summary>Edit activity</summary><form method="POST" action="{{ route($routePrefix.'.community-projects.activities.update', [$project, $activity]) }}" class="stack-form" style="min-width:18rem">@csrf @method('PUT')<label class="field-group"><span>Title</span><input name="title" value="{{ $activity->title }}" required maxlength="255"></label><label class="field-group"><span>Description</span><textarea name="description" rows="2" maxlength="3000">{{ $activity->description }}</textarea></label><label class="field-group"><span>Scheduled date</span><input type="date" name="scheduled_date" value="{{ $activity->scheduled_date?->toDateString() }}"></label><label class="field-group"><span>Status</span><select name="status">@foreach($activityStatuses as $value => $label)<option value="{{ $value }}" @selected($activity->status === $value)>{{ $label }}</option>@endforeach</select></label><label class="field-group"><span>Accomplishment notes</span><textarea name="accomplishment_notes" rows="3" maxlength="3000">{{ $activity->accomplishment_notes }}</textarea></label><button class="primary-button compact" type="submit">Save activity</button></form></details>@endif</td><td>{{ $activity->creator?->name ?? 'System' }}</td></tr>@empty<tr><td colspan="5"><div class="empty-state"><strong>No activities recorded</strong><span>Add the implementation work plan after project review.</span></div></td></tr>@endforelse</tbody></table></div>
        @if($canManageImplementation)<form method="POST" action="{{ route($routePrefix.'.community-projects.activities.store', $project) }}" class="report-filter-grid" style="padding:1.25rem">@csrf<label class="field-group"><span>Activity title</span><input name="title" required maxlength="255"></label><label class="field-group"><span>Scheduled date</span><input type="date" name="scheduled_date"></label><label class="field-group"><span>Status</span><select name="status" required>@foreach($activityStatuses as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></label><label class="field-group full"><span>Description</span><textarea name="description" rows="2" maxlength="3000"></textarea></label><label class="field-group full"><span>Accomplishment notes</span><textarea name="accomplishment_notes" rows="2" maxlength="3000"></textarea></label><div><button class="primary-button" type="submit">Add activity</button></div></form>@endif
    </section>

    <section class="card user-table-card" style="margin-top:1.25rem">
        <div class="section-heading"><div><span class="eyebrow">Documentation management</span><h3>Project accomplishment files</h3><p>Keep reports, photos, certificates, and supporting files attached to this project and, when applicable, a specific activity.</p></div></div>
        <div class="table-wrap"><table class="data-table"><thead><tr><th>Documentation</th><th>Category</th><th>Linked activity</th><th>Uploaded by</th><th>Action</th></tr></thead><tbody>
            @forelse($project->documents as $document)
                <tr>
                    <td><strong>{{ $document->title }}</strong><small class="table-secondary-line">{{ $document->original_name }} · {{ $document->formattedSize() }}</small>@if($document->description)<small class="table-secondary-line">{{ $document->description }}</small>@endif</td>
                    <td>{{ $document->categoryLabel() }}</td>
                    <td>{{ $document->activity?->title ?? 'Project-level' }}</td>
                    <td>{{ $document->uploader?->name ?? 'Former user' }}<small class="table-secondary-line">{{ $document->created_at->format('M d, Y g:i A') }}</small></td>
                    <td><a class="table-action" href="{{ route($routePrefix.'.community-projects.documents.download', [$project, $document]) }}">Download</a>@if($canManageImplementation || $document->uploaded_by === auth()->id())<form method="POST" action="{{ route($routePrefix.'.community-projects.documents.destroy', [$project, $document]) }}" style="display:inline" onsubmit="return confirm('Remove this project documentation file?')">@csrf @method('DELETE')<button class="text-link" type="submit">Remove</button></form>@endif</td>
                </tr>
            @empty
                <tr><td colspan="5"><div class="empty-state"><strong>No accomplishment documentation yet</strong><span>Upload reports, activity photos, certificates, or supporting files after project approval.</span></div></td></tr>
            @endforelse
        </tbody></table></div>
        @if($canUploadDocumentation)
            <form method="POST" action="{{ route($routePrefix.'.community-projects.documents.store', $project) }}" enctype="multipart/form-data" class="report-filter-grid" style="padding:1.25rem">
                @csrf
                <label class="field-group"><span>Category</span><select name="category" required>@foreach($documentCategories as $value => $label)<option value="{{ $value }}" @selected(old('category') === $value)>{{ $label }}</option>@endforeach</select></label>
                <label class="field-group"><span>Documentation title</span><input name="title" value="{{ old('title') }}" required maxlength="255" placeholder="e.g. Literacy Session Accomplishment Report"></label>
                <label class="field-group"><span>Related activity</span><select name="community_project_activity_id"><option value="">Project-level documentation</option>@foreach($project->activities as $activity)<option value="{{ $activity->id }}" @selected((string)old('community_project_activity_id') === (string)$activity->id)>{{ $activity->title }}</option>@endforeach</select></label>
                <label class="field-group"><span>File</span><input type="file" name="file" required accept=".pdf,.jpg,.jpeg,.png,.doc,.docx,.xls,.xlsx,.csv"><small>PDF, image, Word, Excel, or CSV · maximum 15 MB</small></label>
                <label class="field-group full"><span>Description</span><textarea name="description" rows="2" maxlength="3000" placeholder="Briefly explain what this file documents.">{{ old('description') }}</textarea></label>
                <div>@if($project->approval_status === 'approved')<button class="primary-button" type="submit">Upload documentation</button>@else<span class="document-status">Project approval is required before upload.</span>@endif</div>
            </form>
        @endif
    </section>
@endsection
