<div class="form-grid">
    <label class="field-group"><span>NSTP component</span><select name="component_id" required>@foreach($components as $component)<option value="{{ $component->id }}" @selected((int) old('component_id', $selectedComponent) === $component->id)>{{ $component->code }} — {{ $component->name }}</option>@endforeach</select>@error('component_id')<small class="field-error">{{ $message }}</small>@enderror</label>
    <label class="field-group"><span>Facilitator</span><select name="facilitator_id"><option value="">Unassigned</option>@foreach($facilitators as $facilitator)<option value="{{ $facilitator->id }}" @selected((int) old('facilitator_id', $section?->facilitator_id) === $facilitator->id)>{{ $facilitator->name }}</option>@endforeach</select>@error('facilitator_id')<small class="field-error">{{ $message }}</small>@enderror</label>
    <label class="field-group"><span>Section code</span><input name="code" value="{{ old('code', $section?->code) }}" maxlength="30" placeholder="CWTS-01" required>@error('code')<small class="field-error">{{ $message }}</small>@enderror</label>
    <label class="field-group"><span>Section name</span><input name="name" value="{{ old('name', $section?->name) }}" maxlength="100" placeholder="CWTS Section 1" required>@error('name')<small class="field-error">{{ $message }}</small>@enderror</label>
    <label class="field-group"><span>Academic year</span><input name="academic_year" value="{{ old('academic_year', $defaultAcademicYear) }}" maxlength="9" pattern="\d{4}-\d{4}" placeholder="2026-2027" required>@error('academic_year')<small class="field-error">{{ $message }}</small>@enderror</label>
    <label class="field-group"><span>Semester</span><select name="semester" required>@foreach(\App\Models\NstpSection::SEMESTERS as $value => $label)<option value="{{ $value }}" @selected(old('semester', $section?->semester ?? 'first') === $value)>{{ $label }}</option>@endforeach</select>@error('semester')<small class="field-error">{{ $message }}</small>@enderror</label>
    <label class="field-group"><span>Student capacity</span><input type="number" name="capacity" value="{{ old('capacity', $section?->capacity ?? 40) }}" min="1" max="200" required>@error('capacity')<small class="field-error">{{ $message }}</small>@enderror</label>
    <label class="field-group"><span>Section status</span><select name="status" required><option value="active" @selected(old('status', $section?->status ?? 'active') === 'active')>Active</option><option value="inactive" @selected(old('status', $section?->status ?? 'active') === 'inactive')>Inactive</option></select>@error('status')<small class="field-error">{{ $message }}</small>@enderror</label>
</div>
