@extends($layout)

@section('title', 'Honorarium Status')
@section('page-title', auth()->user()->isFacilitator() ? 'My Honorarium Status' : 'Facilitator Honorarium Documents')

@section('content')
<section class="welcome-banner"><div><span class="eyebrow">University Cashier handoff</span><h2>{{ auth()->user()->isFacilitator() ? 'Track your honorarium document status' : 'Prepare honorarium documents for the cashier' }}</h2><p>{{ auth()->user()->isFacilitator() ? 'View read-only document-processing updates from the Coordinator and NSTP Admin. Approval and payment are handled by the University Cashier.' : 'Create requests, prepare disbursement vouchers and supporting references, then record when the package is forwarded to the University Cashier. The system does not approve or disburse funds.' }}</p></div>@if($canCreateRequests)<a class="primary-button" href="{{ route($routePrefix.'.honoraria.create') }}">Create honorarium request</a>@endif</section>

@if(auth()->user()->isFacilitator())
    <section class="card user-table-card">
        <div class="section-heading"><div><span class="eyebrow">Read-only status</span><h3>Honorarium document history</h3><p>For approval, release, or payment concerns, coordinate with the University Cashier through the NSTP Office.</p></div></div>
        <div class="table-wrap"><table class="data-table"><thead><tr><th>Reference</th><th>Component</th><th>Academic term</th><th>Service period</th><th>Status</th><th>Last updated</th></tr></thead><tbody>@forelse($records as $record)<tr><td><strong>{{ $record->reference_number }}</strong></td><td>{{ $record->component->code }}</td><td>{{ $record->academic_year }} · {{ $record->semesterLabel() }}</td><td>{{ $record->period_start->format('M d, Y') }} – {{ $record->period_end->format('M d, Y') }}</td><td><span class="status-badge {{ $record->status === 'forwarded_to_cashier' ? 'active' : 'inactive' }}"><i></i>{{ $record->statusLabel() }}</span>@if($record->status === 'returned_for_correction')<small class="table-secondary-line">Please coordinate with the NSTP Office.</small>@endif</td><td>{{ $record->updated_at->format('M d, Y g:i A') }}</td></tr>@empty<tr><td colspan="6"><div class="empty-state"><strong>No honorarium record yet</strong><span>Your processing status will appear after a Coordinator or NSTP Admin creates a request.</span></div></td></tr>@endforelse</tbody></table></div>
    </section>
@else
    <section class="metric-grid" aria-label="Honorarium processing summary">
        <article class="metric-card"><span class="metric-icon blue">▤</span><div><small>Total requests</small><strong>{{ $metrics['total'] }}</strong><p>Within your scope</p></div></article>
        <article class="metric-card"><span class="metric-icon orange">◷</span><div><small>For preparation</small><strong>{{ $metrics['for_preparation'] }}</strong><p>Needs document preparation</p></div></article>
        <article class="metric-card"><span class="metric-icon violet">▤</span><div><small>Documents prepared</small><strong>{{ $metrics['prepared'] }}</strong><p>Voucher package is ready</p></div></article>
        <article class="metric-card"><span class="metric-icon green">→</span><div><small>Forwarded</small><strong>{{ $metrics['forwarded'] }}</strong><p>Sent to University Cashier</p></div></article>
    </section>
    <section class="card user-table-card">
        <div class="section-heading"><div><span class="eyebrow">Cashier document records</span><h3>Honorarium requests and vouchers</h3></div></div>
        <div class="table-wrap"><table class="data-table"><thead><tr><th>Request</th><th>Facilitator</th><th>Term and period</th><th>Amounts</th><th>Status</th><th>Document preparation</th></tr></thead><tbody>
        @forelse($records as $record)
            <tr><td><strong>{{ $record->reference_number }}</strong><small class="table-secondary-line">Created by {{ $record->requester?->name ?? 'Former user' }} · {{ $record->requested_at->format('M d, Y') }}</small></td><td>{{ $record->facilitator->name }}<small class="table-secondary-line">{{ $record->component->code }}</small></td><td>{{ $record->academic_year }} · {{ $record->semesterLabel() }}<small class="table-secondary-line">{{ $record->period_start->format('M d') }} – {{ $record->period_end->format('M d, Y') }}</small></td><td>Gross ₱{{ number_format((float)$record->gross_amount, 2) }}<small class="table-secondary-line">Deductions ₱{{ number_format((float)$record->deductions, 2) }} · Net ₱{{ number_format((float)$record->net_amount, 2) }}</small></td><td><strong>{{ $record->statusLabel() }}</strong>@if($record->preparation_notes)<small class="table-secondary-line">{{ $record->preparation_notes }}</small>@endif @if($record->disbursement_voucher_number)<small class="table-secondary-line">DV: {{ $record->disbursement_voucher_number }}</small>@endif</td><td>
                @if(in_array($record->status, ['documents_prepared', 'forwarded_to_cashier'], true))<a class="table-action" href="{{ route($routePrefix.'.honoraria.voucher', $record) }}">Download cashier voucher</a>@endif
                @if($canPrepareDocuments)<details><summary>{{ $record->prepared_at ? 'Update document package' : 'Prepare cashier documents' }}</summary><form method="POST" action="{{ route($routePrefix.'.honoraria.documents.update', $record) }}" class="stack-form" style="min-width:20rem">@csrf @method('PUT')<label class="field-group"><span>Processing status</span><select name="status"><option value="documents_prepared" @selected($record->status === 'documents_prepared')>Documents prepared</option><option value="forwarded_to_cashier" @selected($record->status === 'forwarded_to_cashier')>Forwarded to University Cashier</option><option value="returned_for_correction" @selected($record->status === 'returned_for_correction')>Returned for correction</option></select></label><label class="field-group"><span>Disbursement voucher number</span><input name="disbursement_voucher_number" value="{{ $record->disbursement_voucher_number }}" maxlength="100"></label><label class="field-group"><span>Obligation request number</span><input name="obligation_request_number" value="{{ $record->obligation_request_number }}" maxlength="100"></label><label class="field-group"><span>Payroll/reference number</span><input name="payroll_reference" value="{{ $record->payroll_reference }}" maxlength="100"></label><label class="field-group"><span>Forwarded to cashier at</span><input type="datetime-local" name="cashier_forwarded_at" value="{{ $record->cashier_forwarded_at?->format('Y-m-d\TH:i') }}"></label><label class="field-group"><span>Preparation notes</span><textarea name="preparation_notes" rows="3" maxlength="3000">{{ $record->preparation_notes }}</textarea></label><button class="primary-button compact" type="submit">Save document status</button></form></details>@endif
            </td></tr>
        @empty<tr><td colspan="6"><div class="empty-state"><strong>No honorarium requests</strong><span>Create the first facilitator payment request for the active term.</span></div></td></tr>@endforelse
        </tbody></table></div>
    </section>
@endif
@endsection
