<?php

return [
    'definitions' => [
        'accounts.staff' => ['group' => 'People & Registration', 'label' => 'Manage staff accounts', 'bases' => ['nstp_admin']],
        'accounts.students' => ['group' => 'People & Registration', 'label' => 'Manage student accounts and imports', 'bases' => ['nstp_admin']],
        'registrations.review' => ['group' => 'People & Registration', 'label' => 'Review student registrations', 'bases' => ['nstp_admin']],
        'documents.configure' => ['group' => 'Documents & Forms', 'label' => 'Configure documents and downloadable forms', 'bases' => ['nstp_admin']],
        'documents.review' => ['group' => 'Documents & Forms', 'label' => 'Review configurable document submissions', 'bases' => ['nstp_admin']],
        'reviews.configure' => ['group' => 'Documents & Forms', 'label' => 'Configure registration and document review categories', 'bases' => ['nstp_admin']],
        'workflows.configure' => ['group' => 'Configuration', 'label' => 'Configure operational workflow rules', 'bases' => ['nstp_admin']],
        'notifications.configure' => ['group' => 'Configuration', 'label' => 'Configure notification rules, channels, templates, and schedules', 'bases' => ['nstp_admin']],
        'policies.configure' => ['group' => 'Configuration', 'label' => 'Configure institution policies and student requirements', 'bases' => ['nstp_admin']],
        'landing.configure' => ['group' => 'Configuration', 'label' => 'Edit and publish public landing page content', 'bases' => ['nstp_admin', 'coordinator']],
        'program.components' => ['group' => 'Program Operations', 'label' => 'Manage NSTP components', 'bases' => ['nstp_admin', 'coordinator']],
        'program.sections' => ['group' => 'Program Operations', 'label' => 'Manage sections and sectioning', 'bases' => ['nstp_admin', 'coordinator']],
        'program.schedules' => ['group' => 'Program Operations', 'label' => 'Manage schedules', 'bases' => ['nstp_admin', 'coordinator']],
        'learning.attendance' => ['group' => 'Learning & Assessment', 'label' => 'Manage or view attendance', 'bases' => ['nstp_admin', 'coordinator', 'facilitator', 'student']],
        'learning.materials' => ['group' => 'Learning & Assessment', 'label' => 'Manage or view learning materials', 'bases' => ['nstp_admin', 'coordinator', 'facilitator', 'student']],
        'learning.assessments' => ['group' => 'Learning & Assessment', 'label' => 'Manage or take assessments', 'bases' => ['nstp_admin', 'coordinator', 'facilitator', 'student']],
        'learning.grades' => ['group' => 'Learning & Assessment', 'label' => 'Manage or view grades', 'bases' => ['nstp_admin', 'coordinator', 'facilitator', 'student']],
        'learning.omr' => ['group' => 'Learning & Assessment', 'label' => 'Use answer-sheet scanner', 'bases' => ['coordinator', 'facilitator']],
        'monitoring.performance' => ['group' => 'Monitoring', 'label' => 'View student performance monitoring', 'bases' => ['coordinator']],
        'rotc.approvals' => ['group' => 'Monitoring', 'label' => 'Review ROTC approval requests', 'bases' => ['nstp_admin', 'coordinator']],
        'reports.view' => ['group' => 'Reports & Records', 'label' => 'View and export reports', 'bases' => ['nstp_admin', 'coordinator', 'facilitator', 'student']],
        'serial_numbers.manage' => ['group' => 'Reports & Records', 'label' => 'Upload official serial-number files and encode graduate serial numbers', 'bases' => ['nstp_admin', 'coordinator']],
        'records.archives' => ['group' => 'Reports & Records', 'label' => 'Manage archived records', 'bases' => ['nstp_admin']],
        'communication.announcements' => ['group' => 'Communication', 'label' => 'Manage or view announcements', 'bases' => ['nstp_admin', 'coordinator', 'facilitator', 'student']],
        'communication.messages' => ['group' => 'Communication', 'label' => 'Use direct and group messages', 'bases' => ['nstp_admin', 'coordinator', 'facilitator', 'student']],
        'ai.use' => ['group' => 'Communication', 'label' => 'Use AI Assistant and AI learning tools', 'bases' => ['nstp_admin', 'coordinator', 'facilitator', 'student']],
        'student.profile' => ['group' => 'Student Services', 'label' => 'Manage own student profile and documents', 'bases' => ['student']],
        'student.component' => ['group' => 'Student Services', 'label' => 'Select NSTP component', 'bases' => ['student']],
        'student.documents' => ['group' => 'Student Services', 'label' => 'Download forms and submit documents', 'bases' => ['student']],
    ],

    'defaults' => [
        'super_admin' => ['*'],
        'nstp_admin' => [
            'accounts.staff', 'accounts.students', 'registrations.review', 'documents.configure', 'documents.review', 'reviews.configure', 'workflows.configure', 'notifications.configure', 'policies.configure', 'landing.configure', 'program.components',
            'program.sections', 'program.schedules', 'learning.attendance', 'learning.materials',
            'learning.assessments', 'learning.grades', 'rotc.approvals', 'reports.view', 'serial_numbers.manage', 'records.archives',
            'communication.announcements', 'communication.messages', 'ai.use',
        ],
        'coordinator' => [
            'program.components', 'program.sections', 'program.schedules', 'learning.attendance',
            'learning.materials', 'learning.assessments', 'learning.grades', 'learning.omr',
            'monitoring.performance', 'rotc.approvals', 'reports.view', 'serial_numbers.manage',
            'communication.announcements', 'communication.messages', 'landing.configure', 'ai.use',
        ],
        'facilitator' => [
            'learning.attendance', 'learning.materials', 'learning.assessments', 'learning.grades',
            'learning.omr', 'reports.view', 'communication.announcements',
            'communication.messages', 'ai.use',
        ],
        'student' => [
            'learning.attendance', 'learning.materials', 'learning.assessments', 'learning.grades',
            'reports.view', 'communication.announcements', 'communication.messages', 'ai.use',
            'student.profile', 'student.component', 'student.documents',
        ],
    ],

    'route_map' => [
        'admin.roles.*' => 'roles.manage',
        'admin.users.*' => 'accounts.staff',
        'admin.students.*' => 'accounts.students',
        'admin.registrations.*' => 'registrations.review',
        'admin.document-forms.*' => 'documents.configure',
        'admin.document-reviews.*' => 'documents.review',
        'admin.review-categories.*' => 'reviews.configure',
        'admin.workflows.*' => 'workflows.configure',
        'admin.notification-rules.*' => 'notifications.configure',
        'admin.policies.*' => 'policies.configure',
        'admin.landing-page.*' => 'landing.configure',
        'admin.components.*' => 'program.components',
        'admin.sections.*' => 'program.sections',
        'admin.sectioning.*' => 'program.sections',
        'admin.schedules.*' => 'program.schedules',
        'admin.attendance.*' => 'learning.attendance',
        'admin.materials.*' => 'learning.materials',
        'admin.assessments.*' => 'learning.assessments',
        'admin.grades.*' => 'learning.grades',
        'admin.rotc-approvals.*' => 'rotc.approvals',
        'admin.reports.*' => 'reports.view',
        'admin.ched-applications.*' => 'reports.view',
        'admin.serial-numbers.*' => 'serial_numbers.manage',
        'admin.archives.*' => 'records.archives',
        'admin.announcements.*' => 'communication.announcements',
        'admin.messages.*' => 'communication.messages',
        'nstp_admin.accounts.*' => 'accounts.staff',
        'nstp_admin.students.*' => 'accounts.students',
        'nstp_admin.registrations.*' => 'registrations.review',
        'nstp_admin.document-forms.*' => 'documents.configure',
        'nstp_admin.document-reviews.*' => 'documents.review',
        'nstp_admin.review-categories.*' => 'reviews.configure',
        'nstp_admin.workflows.*' => 'workflows.configure',
        'nstp_admin.notification-rules.*' => 'notifications.configure',
        'nstp_admin.policies.*' => 'policies.configure',
        'nstp_admin.landing-page.*' => 'landing.configure',
        'nstp_admin.components.*' => 'program.components',
        'nstp_admin.sections.*' => 'program.sections',
        'nstp_admin.sectioning.*' => 'program.sections',
        'nstp_admin.schedules.*' => 'program.schedules',
        'nstp_admin.attendance.*' => 'learning.attendance',
        'nstp_admin.materials.*' => 'learning.materials',
        'nstp_admin.assessments.*' => 'learning.assessments',
        'nstp_admin.grades.*' => 'learning.grades',
        'nstp_admin.rotc-approvals.*' => 'rotc.approvals',
        'nstp_admin.reports.*' => 'reports.view',
        'nstp_admin.ched-applications.*' => 'reports.view',
        'nstp_admin.serial-numbers.*' => 'serial_numbers.manage',
        'nstp_admin.announcements.*' => 'communication.announcements',
        'nstp_admin.messages.*' => 'communication.messages',
        'coordinator.components.*' => 'program.components',
        'coordinator.accounts.*' => 'program.components',
        'coordinator.sections.*' => 'program.sections',
        'coordinator.schedules.*' => 'program.schedules',
        'coordinator.attendance.*' => 'learning.attendance',
        'coordinator.materials.*' => 'learning.materials',
        'coordinator.assessments.*' => 'learning.assessments',
        'coordinator.grades.*' => 'learning.grades',
        'coordinator.omr.*' => 'learning.omr',
        'coordinator.performance.*' => 'monitoring.performance',
        'coordinator.rotc-approvals.*' => 'rotc.approvals',
        'coordinator.reports.*' => 'reports.view',
        'coordinator.serial-numbers.*' => 'serial_numbers.manage',
        'coordinator.announcements.*' => 'communication.announcements',
        'coordinator.messages.*' => 'communication.messages',
        'coordinator.landing-page.*' => 'landing.configure',
        'facilitator.students.*' => 'learning.grades',
        'facilitator.attendance.*' => 'learning.attendance',
        'facilitator.materials.*' => 'learning.materials',
        'facilitator.assessments.*' => 'learning.assessments',
        'facilitator.grades.*' => 'learning.grades',
        'facilitator.omr.*' => 'learning.omr',
        'facilitator.reports.*' => 'reports.view',
        'facilitator.announcements.*' => 'communication.announcements',
        'facilitator.messages.*' => 'communication.messages',
        'student.profile.*' => 'student.profile',
        'student.required-documents.*' => 'student.profile',
        'student.component.*' => 'student.component',
        'student.documents.*' => 'student.documents',
        'student.attendance.*' => 'learning.attendance',
        'student.id-card' => 'learning.attendance',
        'student.materials.*' => 'learning.materials',
        'student.assessments.*' => 'learning.assessments',
        'student.grades.*' => 'learning.grades',
        'student.reports.*' => 'reports.view',
        'student.recommendations.*' => 'ai.use',
        'student.proposal-guide.*' => 'ai.use',
        'student.announcements.*' => 'communication.announcements',
        'student.messages.*' => 'communication.messages',
        'ai-assistant.*' => 'ai.use',
    ],
];
