<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title', 'Coordinator') · {{ config('app.name') }}</title>
    <link rel="icon" type="image/png" href="{{ asset('images/branding/tau-logo.png') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="{{ asset('css/app.css') }}?v={{ filemtime(public_path('css/app.css')) }}"><x-theme-init />
</head>
<body class="admin-body portal-coordinator" data-coordinator-tour-root><div class="app-shell">
    <aside class="sidebar" id="sidebar"><button class="sidebar-toggle" type="button" aria-controls="sidebar" aria-expanded="true" aria-label="Collapse sidebar">‹</button>
        <a class="brand" href="{{ route('coordinator.dashboard') }}"><x-system-brand subtitle="Coordinator Portal" /></a>
        <div class="role-card"><x-user-avatar :user="auth()->user()" /><span><strong>{{ auth()->user()->name }}</strong><small>{{ auth()->user()->roleLabel() }}</small></span></div>
        <nav class="main-nav" aria-label="Coordinator navigation">
            <p class="nav-label">Overview</p>
            <a class="nav-link {{ request()->routeIs('coordinator.dashboard') ? 'active' : '' }}" href="{{ route('coordinator.dashboard') }}" data-coordinator-tour="dashboard"><span class="nav-icon">⌂</span> Dashboard</a>
            <p class="nav-label">Program Oversight</p>
            @permission('program.components')<a class="nav-link {{ request()->routeIs('coordinator.components.*') ? 'active' : '' }}" href="{{ route('coordinator.components.index') }}" data-coordinator-tour="components"><span class="nav-icon">◉</span> Components</a>
            <a class="nav-link {{ request()->routeIs('coordinator.accounts.*') ? 'active' : '' }}" href="{{ route('coordinator.accounts.index') }}" data-coordinator-tour="accounts"><span class="nav-icon">♙</span> Facilitators & Students</a>@endpermission
            @permission('program.sections')<a class="nav-link {{ request()->routeIs('coordinator.sections.*') ? 'active' : '' }}" href="{{ route('coordinator.sections.index') }}" data-coordinator-tour="sections"><span class="nav-icon">▦</span> Sections & Facilitators</a>@endpermission
            @permission('program.schedules')<a class="nav-link {{ request()->routeIs('coordinator.schedules.*') ? 'active' : '' }}" href="{{ route('coordinator.schedules.index') }}" data-coordinator-tour="scheduling"><span class="nav-icon">◷</span> Scheduling</a>@endpermission
            @permission('rotc.approvals')
                @if(auth()->user()->nstpComponent?->code === 'ROTC')<a class="nav-link {{ request()->routeIs('coordinator.rotc-approvals.*') ? 'active' : '' }}" href="{{ route('coordinator.rotc-approvals.index') }}"><span class="nav-icon">✓</span> ROTC Approvals</a>@endif
            @endpermission
            <a class="nav-link {{ request()->routeIs('coordinator.community-projects.*') ? 'active' : '' }}" href="{{ route('coordinator.community-projects.index') }}"><span class="nav-icon">⌂</span> Community Projects</a>
            <a class="nav-link {{ request()->routeIs('coordinator.project-tasks.*') ? 'active' : '' }}" href="{{ route('coordinator.project-tasks.index') }}"><span class="nav-icon">✓</span> Task Monitoring</a>
            <p class="nav-label">Attendance & Learning</p>
            @permission('learning.attendance')<a class="nav-link {{ request()->routeIs('coordinator.attendance.*') ? 'active' : '' }}" href="{{ route('notifications.categories.open', 'attendance') }}" data-coordinator-tour="attendance"><span class="nav-icon">▣</span> Attendance @if($sidebarPortalNotificationCounts['attendance'])<span class="nav-count">{{ $sidebarPortalNotificationCounts['attendance'] > 99 ? '99+' : $sidebarPortalNotificationCounts['attendance'] }}</span>@endif</a>@endpermission
            @permission('learning.materials')<a class="nav-link {{ request()->routeIs('coordinator.materials.*') ? 'active' : '' }}" href="{{ route('notifications.categories.open', 'materials') }}"><span class="nav-icon">▤</span> Learning Materials @if($sidebarPortalNotificationCounts['materials'])<span class="nav-count">{{ $sidebarPortalNotificationCounts['materials'] > 99 ? '99+' : $sidebarPortalNotificationCounts['materials'] }}</span>@endif</a>@endpermission
            <p class="nav-label">Assessment & Grading</p>
            @permission('learning.omr')<a class="nav-link {{ request()->routeIs('coordinator.omr.*') ? 'active' : '' }}" href="{{ route('coordinator.omr.index') }}" data-coordinator-tour="omr"><span class="nav-icon">▦</span> Answer Sheet Scanner</a>@endpermission
            @permission('monitoring.performance')<a class="nav-link {{ request()->routeIs('coordinator.performance.*') ? 'active' : '' }}" href="{{ route('coordinator.performance.index') }}" data-coordinator-tour="performance"><span class="nav-icon">◎</span> Performance & Grades</a>@endpermission
            @permission('learning.assessments')<a class="nav-link {{ request()->routeIs('coordinator.assessments.index', 'coordinator.assessments.show') ? 'active' : '' }}" href="{{ route('coordinator.assessments.index') }}"><span class="nav-icon">▤</span> Assessment Review</a>@endpermission
            @permission('learning.grades')<a class="nav-link {{ request()->routeIs('coordinator.grades.*') ? 'active' : '' }}" href="{{ route('notifications.categories.open', 'assessments') }}"><span class="nav-icon">✎</span> Grading Setup @if($sidebarPortalNotificationCounts['assessments'])<span class="nav-count">{{ $sidebarPortalNotificationCounts['assessments'] > 99 ? '99+' : $sidebarPortalNotificationCounts['assessments'] }}</span>@endif</a>@endpermission
            <p class="nav-label">Reports</p>
            @permission('reports.view')<a class="nav-link {{ request()->routeIs('coordinator.reports.*') ? 'active' : '' }}" href="{{ route('coordinator.reports.index') }}" data-coordinator-tour="reports"><span class="nav-icon">▤</span> Reports Center</a>@endpermission
            <p class="nav-label">Communication</p>
            @permission('communication.announcements')<a class="nav-link {{ request()->routeIs('coordinator.announcements.*') ? 'active' : '' }}" href="{{ route('notifications.categories.open', 'announcements') }}"><span class="nav-icon">◫</span> Announcements @if($sidebarPortalNotificationCounts['announcements'])<span class="nav-count">{{ $sidebarPortalNotificationCounts['announcements'] > 99 ? '99+' : $sidebarPortalNotificationCounts['announcements'] }}</span>@endif</a>@endpermission
            @permission('communication.messages')<a class="nav-link {{ request()->routeIs('coordinator.messages.*') ? 'active' : '' }}" href="{{ route('notifications.categories.open', 'messages') }}"><span class="nav-icon">◇</span> Messages @if($sidebarUnreadMessageCount > 0)<span class="nav-count" data-unread-message-count="{{ $sidebarUnreadMessageCount }}">{{ $sidebarUnreadMessageCount > 99 ? '99+' : $sidebarUnreadMessageCount }}</span>@endif</a>@endpermission
            @permission('ai.use')<a class="nav-link {{ request()->routeIs('ai-assistant.*') ? 'active' : '' }}" href="{{ route('ai-assistant.index') }}" data-coordinator-tour="ai"><span class="nav-icon">✦</span> AI Assistant</a>@endpermission
            <p class="nav-label">Account</p>
            <a class="nav-link {{ request()->routeIs('coordinator.profile.*') ? 'active' : '' }}" href="{{ route('coordinator.profile.edit') }}"><span class="nav-icon">⚙</span> Profile & Security</a>
            <a class="nav-link {{ request()->routeIs('coordinator.system-guide') ? 'active' : '' }}" href="{{ route('coordinator.system-guide') }}" data-coordinator-tour="guide"><span class="nav-icon">?</span> System Guide</a>
        </nav>
        <form method="POST" action="{{ route('logout') }}" class="logout-form">@csrf<button type="submit" class="nav-link logout"><span class="nav-icon">↪</span> Sign out</button></form>
    </aside>
    <button class="sidebar-backdrop" type="button" aria-label="Close navigation" data-sidebar-backdrop hidden></button>
    <main class="main-content"><header class="topbar"><button class="menu-button" type="button" aria-controls="sidebar" aria-expanded="false" aria-label="Toggle navigation">☰</button><div class="topbar-title" data-coordinator-tour-page-title><small>TAU NSTP / Coordinator</small><h1>@yield('page-title', 'Dashboard')</h1></div><x-notification-bell /><x-theme-toggle /><button class="admin-tour-topbar-button" type="button" data-start-coordinator-tour><span aria-hidden="true">?</span> Guided Tour</button><div class="topbar-status"><span></span> Monitoring & QR scanning</div></header>@if(session('status'))<div class="alert success">{{ session('status') }}</div>@endif @if($errors->any())<div class="alert danger">{{ $errors->first() }}</div>@endif @yield('content')<footer class="app-footer">© {{ date('Y') }} Tarlac Agricultural University · National Service Training Program</footer></main>
</div>@permission('ai.use')<x-ai-chat-widget />@endpermission<script src="{{ asset('js/sidebar.js') }}"></script><script src="{{ asset('js/theme.js') }}"></script><script src="{{ asset('js/table-sort.js') }}?v={{ filemtime(public_path('js/table-sort.js')) }}"></script><script src="{{ asset('js/admin-tour.js') }}?v={{ filemtime(public_path('js/admin-tour.js')) }}"></script></body></html>
