<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title', 'Facilitator') · {{ config('app.name') }}</title>
    <link rel="icon" type="image/png" sizes="64x64" href="{{ asset('images/snapie-logo-64.png') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="{{ asset('css/app.css') }}?v={{ filemtime(public_path('css/app.css')) }}">
</head>
<body class="admin-body"><div class="app-shell">
    <aside class="sidebar" id="sidebar"><button class="sidebar-toggle" type="button" aria-controls="sidebar" aria-expanded="true" aria-label="Collapse sidebar">‹</button>
        <a class="brand" href="{{ route('facilitator.dashboard') }}"><img class="brand-logo" src="{{ asset('images/snapie-logo-160.png') }}" alt="SNAPIE logo"><span><strong>Smart NSTP</strong><small>Management Platform</small></span></a>
        <div class="role-card"><x-user-avatar :user="auth()->user()" /><span><strong>{{ auth()->user()->name }}</strong><small>Facilitator</small></span></div>
        <nav class="main-nav" aria-label="Facilitator navigation"><p class="nav-label">Overview</p><a class="nav-link {{ request()->routeIs('facilitator.dashboard') ? 'active' : '' }}" href="{{ route('facilitator.dashboard') }}"><span class="nav-icon">⌂</span> Dashboard</a><p class="nav-label">Teaching</p><a class="nav-link {{ request()->routeIs('facilitator.students.*') ? 'active' : '' }}" href="{{ route('facilitator.students.index') }}"><span class="nav-icon">♙</span> My Students</a><a class="nav-link {{ request()->routeIs('facilitator.attendance.*') ? 'active' : '' }}" href="{{ route('facilitator.attendance.index') }}"><span class="nav-icon">▣</span> Attendance</a><a class="nav-link {{ request()->routeIs('facilitator.materials.*') ? 'active' : '' }}" href="{{ route('facilitator.materials.index') }}"><span class="nav-icon">▤</span> Learning Materials</a><a class="nav-link {{ request()->routeIs('facilitator.assessments.*') ? 'active' : '' }}" href="{{ route('facilitator.assessments.index') }}"><span class="nav-icon">✓</span> Assessments</a><a class="nav-link {{ request()->routeIs('facilitator.omr.*') ? 'active' : '' }}" href="{{ route('facilitator.omr.index') }}"><span class="nav-icon">▦</span> Answer Sheet Scanner</a><a class="nav-link {{ request()->routeIs('facilitator.grades.*') ? 'active' : '' }}" href="{{ route('facilitator.grades.index') }}"><span class="nav-icon">◎</span> Grades</a><p class="nav-label">Account</p><a class="nav-link {{ request()->routeIs('facilitator.profile.*') ? 'active' : '' }}" href="{{ route('facilitator.profile.edit') }}"><span class="nav-icon">⚙</span> Profile & Security</a></nav>
        <form method="POST" action="{{ route('logout') }}" class="logout-form">@csrf<button type="submit" class="nav-link logout"><span class="nav-icon">↪</span> Sign out</button></form>
    </aside>
    <main class="main-content"><header class="topbar"><button class="menu-button" type="button" aria-controls="sidebar" aria-expanded="false" aria-label="Toggle navigation">☰</button><div><small>Smart NSTP / Facilitator</small><h1>@yield('page-title', 'Dashboard')</h1></div><div class="topbar-status"><span></span> System online</div></header>@if(session('status'))<div class="alert success">{{ session('status') }}</div>@endif @if($errors->any())<div class="alert danger">{{ $errors->first() }}</div>@endif @yield('content')<footer class="app-footer">© {{ date('Y') }} Smart NSTP Management and AI-Integrated Platform</footer></main>
</div><script src="{{ asset('js/sidebar.js') }}"></script></body></html>
