<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title', 'Student') · {{ config('app.name') }}</title>
    <link rel="icon" type="image/png" sizes="64x64" href="{{ asset('images/snapie-logo-64.png') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="{{ asset('css/app.css') }}?v={{ filemtime(public_path('css/app.css')) }}"><x-theme-init />
</head>
<body class="admin-body"><div class="app-shell">
    <aside class="sidebar" id="sidebar"><button class="sidebar-toggle" type="button" aria-controls="sidebar" aria-expanded="true" aria-label="Collapse sidebar">‹</button>
        <a class="brand" href="{{ route('student.dashboard') }}"><img class="brand-logo brand-logo-compact" src="{{ asset('images/snapie-logo-160.png') }}" alt="SNAPIE logo"><img class="brand-logo-dark" src="{{ asset('images/snapie-landscape-dark.png') }}" alt="SNAPIE — Smart NSTP Management and AI-Integrated Platform"><span><strong>Smart NSTP</strong><small>Student Learning Portal</small></span></a>
        <div class="role-card"><x-user-avatar :user="auth()->user()" /><span><strong>{{ auth()->user()->name }}</strong><small>Student</small></span></div>
        <nav class="main-nav" aria-label="Student navigation">
            <p class="nav-label">Overview</p><a class="nav-link {{ request()->routeIs('student.dashboard') ? 'active' : '' }}" href="{{ route('student.dashboard') }}"><span class="nav-icon">⌂</span> Dashboard</a><a class="nav-link {{ request()->routeIs('student.component.*') ? 'active' : '' }}" href="{{ route('student.component.edit') }}"><span class="nav-icon">◈</span> NSTP Selection</a>
            <p class="nav-label">Learning</p><a class="nav-link {{ request()->routeIs('student.attendance.*') ? 'active' : '' }}" href="{{ route('notifications.categories.open', 'attendance') }}"><span class="nav-icon">▣</span> Attendance @if($sidebarNotificationCounts['attendance'] > 0)<span class="nav-count" data-attendance-notification-count="{{ $sidebarNotificationCounts['attendance'] }}" aria-label="{{ $sidebarNotificationCounts['attendance'] }} unread attendance notifications">{{ $sidebarNotificationCounts['attendance'] > 99 ? '99+' : $sidebarNotificationCounts['attendance'] }}</span>@endif</a><a class="nav-link {{ request()->routeIs('student.materials.*') ? 'active' : '' }}" href="{{ route('notifications.categories.open', 'materials') }}"><span class="nav-icon">▤</span> Materials @if($sidebarNotificationCounts['materials'] > 0)<span class="nav-count" data-material-notification-count="{{ $sidebarNotificationCounts['materials'] }}" aria-label="{{ $sidebarNotificationCounts['materials'] }} unread material notifications">{{ $sidebarNotificationCounts['materials'] > 99 ? '99+' : $sidebarNotificationCounts['materials'] }}</span>@endif</a><a class="nav-link {{ request()->routeIs('student.assessments.*') ? 'active' : '' }}" href="{{ route('notifications.categories.open', 'assessments') }}"><span class="nav-icon">✓</span> Assessments @php($assessmentNavCount = $sidebarNotificationCounts['assessments'] ?: $sidebarPendingAssessmentCount) @if($assessmentNavCount > 0)<span class="nav-count" data-assessment-notification-count="{{ $sidebarNotificationCounts['assessments'] }}" data-pending-assessment-count="{{ $sidebarPendingAssessmentCount }}" aria-label="{{ $sidebarNotificationCounts['assessments'] ? $sidebarNotificationCounts['assessments'].' unread assessment notifications' : $sidebarPendingAssessmentCount.' pending assessments' }}">{{ $assessmentNavCount > 99 ? '99+' : $assessmentNavCount }}</span>@endif</a><a class="nav-link {{ request()->routeIs('student.grades.*') ? 'active' : '' }}" href="{{ route('student.grades.index') }}"><span class="nav-icon">◎</span> Grades</a>
            <p class="nav-label">Reports</p><a class="nav-link {{ request()->routeIs('student.reports.*') ? 'active' : '' }}" href="{{ route('student.reports.index') }}"><span class="nav-icon">▤</span> Reports</a>
            <p class="nav-label">Communication</p><a class="nav-link {{ request()->routeIs('student.announcements.*') ? 'active' : '' }}" href="{{ route('notifications.categories.open', 'announcements') }}"><span class="nav-icon">◫</span> Announcements @if($sidebarNotificationCounts['announcements'] > 0)<span class="nav-count" data-announcement-notification-count="{{ $sidebarNotificationCounts['announcements'] }}" aria-label="{{ $sidebarNotificationCounts['announcements'] }} unread announcements">{{ $sidebarNotificationCounts['announcements'] > 99 ? '99+' : $sidebarNotificationCounts['announcements'] }}</span>@endif</a><a class="nav-link {{ request()->routeIs('student.messages.*') ? 'active' : '' }}" href="{{ route('notifications.categories.open', 'messages') }}"><span class="nav-icon">◇</span> Messages @if($sidebarUnreadMessageCount > 0)<span class="nav-count" data-unread-message-count="{{ $sidebarUnreadMessageCount }}" aria-label="{{ $sidebarUnreadMessageCount }} unread messages">{{ $sidebarUnreadMessageCount > 99 ? '99+' : $sidebarUnreadMessageCount }}</span>@endif</a><a class="nav-link {{ request()->routeIs('ai-assistant.*') ? 'active' : '' }}" href="{{ route('ai-assistant.index') }}"><span class="nav-icon">✦</span> AI Assistant</a>
            <p class="nav-label">Account</p><a class="nav-link {{ request()->routeIs('student.profile.*') ? 'active' : '' }}" href="{{ route('student.profile.edit') }}"><span class="nav-icon">⚙</span> Profile & Security</a>
        </nav>
        <form method="POST" action="{{ route('logout') }}" class="logout-form">@csrf<button type="submit" class="nav-link logout"><span class="nav-icon">↪</span> Sign out</button></form>
    </aside>
    <main class="main-content"><header class="topbar"><button class="menu-button" type="button" aria-controls="sidebar" aria-expanded="false" aria-label="Toggle navigation">☰</button><div><small>Smart NSTP / Student</small><h1>@yield('page-title', 'Dashboard')</h1></div><x-notification-bell /><x-theme-toggle /><div class="topbar-status"><span></span> System online</div></header>@if(session('status'))<div class="alert success">{{ session('status') }}</div>@endif @if($errors->any())<div class="alert danger">{{ $errors->first() }}</div>@endif @yield('content')<footer class="app-footer">© {{ date('Y') }} Smart NSTP Management and AI-Integrated Platform</footer></main>
</div><x-ai-chat-widget /><script src="{{ asset('js/sidebar.js') }}"></script><script src="{{ asset('js/theme.js') }}"></script></body></html>
